# Generated by Django 6.0.6 on 2026-06-28 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hire_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ishga qabul qilingan sana'),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, choices=[('RECTOR', 'Rektor'), ('VICE_RECTOR', 'Prorektor'), ('DEAN', 'Dekan'), ('HEAD_OF_DEPARTMENT', 'Kafedra mudiri'), ('TEACHER', "O'qituvchi")], default='TEACHER', max_length=30, null=True, verbose_name='Lavozim'),
        ),
        migrations.AlterField(
            model_name='user',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Maosh'),
        ),
    ]
