# Generated by Django 6.0.6 on 2026-07-05 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_login_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, choices=[('RECTOR', 'Rektor'), ('VICE_RECTOR', 'Prorektor'), ('DEAN', 'Dekan'), ('HEAD_OF_DEPARTMENT', 'Kafedra mudiri'), ('TEACHER', "O'qituvchi")], default='ADMIN', max_length=30, null=True, verbose_name='Lavozim'),
        ),
    ]
