# Generated by Django 6.0.6 on 2026-06-28 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('faculties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqti")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('is_deleted', models.BooleanField(default=False, verbose_name="O'chirilgan")),
                ('title', models.CharField(max_length=255, verbose_name='Vazifa nomi')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('priority', models.CharField(choices=[('LOW', 'Past'), ('MEDIUM', "O'rta"), ('HIGH', 'Yuqori')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('CREATED', 'Yaratildi'), ('IN_PROGRESS', 'Jarayonda'), ('COMPLETED', 'Bajarildi')], default='CREATED', max_length=20)),
                ('deadline', models.DateField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Kim tomonidan berilgan')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Xodim')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculties.faculty')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
