# Generated by Django 6.0.6 on 2026-06-28 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqti")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('is_deleted', models.BooleanField(default=False, verbose_name="O'chirilgan")),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Kafedra nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='faculties.faculty', verbose_name='Fakultet')),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL, verbose_name='Kafedra mudiri')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
